This crate provides a high-level interface to {url-pw}[PipeWire]'s {url-pw-api}[API] via {url-wp}[libwireplumber].
Explore the {url-docs}[crate documentation] and the various {url-docs-modules}[modules] for information on how to start using WirePlumber with Rust.

ifeval::["{profile}" != "github"]
[source,toml,subs=attributes+]
----
[dependencies]
wireplumber = { version = "{wprs-versionreq}", features = ["{wprs-versionfeature}"] }
----
endif::[]
ifeval::["{profile}" == "github"]
[source,toml,subs=attributes+]
----
[dependencies]
wireplumber = { version = "{wprs-versionreq}", features = ["{wprs-versionfeature}"], git = "{repository}" }
----
endif::[]

== Examples

Some link:{relative-tree}examples/[examples] are provided that can be built and run via Cargo:

[source,bash]
----
$ cargo run -p wp-examples --bin wpexec -- --help
... snip ...

# try out the default lua example:
$ cargo run -p wp-examples --bin wpexec

# or load the example plugin module:
$ cargo build --workspace --examples &&
  cargo run -p wp-examples --bin wpexec -- --type wireplumber
----

=== External

Projects using wireplumber.rs:

* https://github.com/arcnmx/wireplumber-scripts[WirePlumber Scripts] is a personal collection of plugins, some previously written as Lua scripts.

== Use Cases

This project aims to facilitate the following applications:

* Enabling Rust to be a viable language for writing session management logic as an alternative to the officially supported Lua scripting engine or GObject C APIs
* WirePlumber plugins that can augment or expose APIs for Lua configuration scripts to use
* Stand-alone pipewire clients as an alternative to https://gitlab.freedesktop.org/pipewire/pipewire-rs[pipewire-rs]
