[options]
library = "Wp"
version = "0.5"
target_path = "."
min_cfg_version = "0.5"
work_mode = "normal"
split_build_rs = true
# trust_return_value_nullability = true # TODO: manually go through everything...
single_version_file = "sys/generate/src/Gir.version"
girs_directories = ["sys/generate/src", "gir-files"]

external_libraries = ["GLib", "GObject", "Gio"]
generate = [
	"Wp.Proxy",
	"Wp.GlobalProxy",
	"Wp.Plugin", "Wp.ComponentLoader",
	"Wp.SessionItem", "Wp.SessionItemFeatures",
	"Wp.SiLink", "Wp.SiLinkable", "Wp.SiFactory",
	"Wp.SpaDeviceFeatures",
	"Wp.State",
	"Wp.ProxyFeatures",
	"Wp.CoreFeatures",
	"Wp.PluginFeatures",
	"Wp.NodeFeatures",
	"Wp.Device", "Wp.Endpoint", "Wp.Factory", "Wp.Port",
	"Wp.FeatureActivationTransition",
	"Wp.ImplModule", "Wp.ImplNode",
	"Wp.InitFlags",
	"Wp.InterestMatch", "Wp.InterestMatchFlags", "Wp.InterestEventHook",
	"Wp.BaseDirsFlags",
	"Wp.MetadataFeatures", "Wp.Metadata",
	"Wp.EventHook",
	"Wp.LogTopicFlags",
	"Wp.SettingsFeatures", "Wp.SettingsSpecType",
]

manual = [
	"Wp.SpaIdTable", "Wp.SpaIdValue",
	"Wp.IteratorMethods",
	"Wp.LogTopic",
	"GLib.Error", "GLib.Variant", "GLib.MainContext", "GLib.Source", "GLib.SourceFunc", "GLib.DestroyNotify", "GLib.Quark", "GLib.LogLevelFlags", "GLib.LogField", "GLib.LogWriterOutput",
	"GObject.Closure", "GObject.Value", "GObject.Object",
	"Gio.Cancellable", "Gio.AsyncReadyCallback", "Gio.AsyncResult",
]

[[object]]
name = "Wp.SpaType"
status = "manual"
conversion_type = "scalar"

[[object]]
name = "Wp.Core"
status = "generate"
	[[object.function]]
	pattern = "(clone|get_pw_context|get_pw_core)"
	manual = true
	[[object.function]]
	name = "load_component"
	no_future = true

[[object]]
name = "Wp.Conf"
status = "generate"
	[[object.function]]
	name = "parse_pw_context_sections"
	manual = true

[[object]]
name = "Wp.SiAcquisition"
status = "generate"
	[[object.function]]
	name = "acquire"
	manual = true

[[object]]
name = "Wp.SiAdapter"
status = "generate"
	[[object.function]]
	name = "set_ports_format"
	manual = true

[[object]]
name = "Wp.Transition"
status = "generate"
	[[object.function]]
	pattern = "(new|return_error)"
	manual = true

[[object]]
name = "Wp.SpaDevice"
status = "generate"
	[[object.function]]
	pattern = "(new_wrap|spa_device_handle)"
	manual = true
	[[object.function]]
	name = "new_managed_object_iterator"
	rename = "managed_object_iterator"

[[object]]
name = "Wp.SpaPodParser"
status = "generate"
	[[object.function]]
	name = "new_object"
	ignore = true

[[object]]
name = "Wp.ImplMetadata"
status = "generate"
	[[object.function]]
	name = "new_full"
	constructor = true
	rename = "with_properties"

[[object]]
name = "Wp.Properties"
status = "generate"
	[[object.derive]]
	name = "PartialEq, Eq, PartialOrd, Ord, Hash" # defaults excluding Debug
	[[object.function]]
	pattern = "(.*valist|new|add_keys|add_keys_from_dict|setf|update_keys|update_keys_from_dict)"
	ignore = true
	[[object.function]]
	pattern = "(new_copy|new_copy_dict|new_take|new_wrap|new_wrap_dict|add_from_dict|peek_dict|to_pw_properties|unref_and_take_pw_properties|update_from_dict)"
	manual = true
	[[object.function]]
	name = "new_empty"
	rename = "new"
	[[object.function]]
	name = "new_iterator"
	rename = "items_iterator"
	visibility = "crate"
	[[object.function]]
	name = "add_keys_array"
	rename = "add_keys"
	[[object.function]]
	name = "update_keys_array"
	rename = "update_keys"

[[object]]
name = "Wp.PropertiesItem"
status = "generate"
# TODO: work around gir bug, 0.14 omitted the entire struct properly
cfg_condition = 'feature = "v0_4_2"'

[[object]]
name = "Wp.Iterator"
status = "generate"
	[[object.function]]
	pattern = "(new|new_ptr_array|fold|foreach|get_user_data)"
	manual = true

[[object]]
name = "Wp.Object"
status = "generate"
	[[object.function]]
	name = "activate"
	rename = "object_activate"
	doc_hidden = true
	[[object.function]]
	name = "deactivate"
	rename = "object_deactivate"
	doc_hidden = true
	[[object.function]]
	name = "get_active_features"
	rename = "object_active_features"
	doc_hidden = true
	[[object.function]]
	name = "get_supported_features"
	rename = "object_supported_features"
	doc_hidden = true
	[[object.function]]
	name = "update_features"
	rename = "object_update_features"
	doc_hidden = true

[[object]]
name = "Wp.ObjectManager"
status = "generate"
	[[object.function]]
	pattern = "(add_interest|lookup|new_filtered_iterator)"
	ignore = true
	[[object.function]]
	name = "new_iterator"
	rename = "objects_iterator"
	visibility = "crate"
	[[object.function]]
	name = "new_filtered_iterator_full"
	rename = "filtered_iterator"
	visibility = "crate"
	[[object.function]]
	name = "lookup_full"
	rename = "lookup_object"
	[[object.function]]
	name = "add_interest_full"
	visibility = "crate"

[[object]]
name = "Wp.ObjectInterest"
status = "generate"
	[[object.function]]
	pattern = "(new|matches|new_valist)"
	ignore = true
	[[object.function]]
	name = "new_type"
	rename = "new"
	[[object.function]]
	name = "matches_full"
	rename = "matches"

[[object]]
name = "Wp.ObjectFeatures"
status = "manual"
conversion_type = "scalar"

[[object]]
name = "Wp.PipewireObject"
status = "generate"
	[[object.function]]
	name = "get_property"
	manual = true

[[object]]
name = "Wp.Client"
status = "generate"
	[[object.function]]
	name = "update_permissions"
	ignore = true
	[[object.function]]
	name = "update_permissions_array"
	rename = "update_permissions"
	manual = true

[[object]]
name = "Wp.Node"
status = "generate"
	[[object.function]]
	name = "get_state"
	manual = true
	[[object.function]]
	pattern = "(lookup_port|new_ports_filtered_iterator)"
	ignore = true
	[[object.function]]
	name = "lookup_port_full"
	rename = "lookup_port"
	[[object.function]]
	name = "new_ports_iterator"
	rename = "ports_iterator"
	visibility = "crate"
	[[object.function]]
	name = "new_ports_filtered_iterator_full"
	rename = "ports_filtered_iterator"
	visibility = "crate"

[[object]]
name = "Wp.Link"
status = "generate"
	[[object.function]]
	name = "get_state"
	manual = true

# enums

[[object]]
name = "Wp.ConstraintVerb"
status = "generate"

[[object]]
name = "Wp.ConstraintType"
status = "generate"

[[object]]
name = "Wp.Direction"
status = "generate"

[[object]]
name = "Wp.LibraryErrorEnum"
status = "generate"

[[object]]
name = "Wp.NodeState"
status = "generate"

[[object]]
name = "Wp.DBusState"
status = "generate"

[[object]]
name = "Wp.LinkState"
status = "generate"

[[object]]
name = "Wp.SiAdapterPortsState"
status = "generate"

[[object]]
name = "Wp.TransitionStep"
status = "generate"

# flags

[[object]]
name = "Wp.LinkFeatures"
status = "generate"
version = "" # fails to parse, so removes cfg
	[[object.member]]
	# instead, apply the version cfg to all defined bits instead
	pattern = ".*"
	version = "0.4.11"

# unsupported methods (mostly varargs fns)

[[object]]
name = "Wp.SpaJson"
status = "generate"
trust_return_value_nullability = true
	[[object.derive]]
	name = "PartialEq, Eq, PartialOrd, Ord, Hash" # defaults excluding Debug
	[[object.function]]
	pattern = "(.*valist|new_array|new_object|object_get|parse_array|parse_object)"
	ignore = true
	[[object.function]]
	pattern = "(new_wrap|new_wrap_string|new_from_string|get_spa_json|get_data)"
	manual = true
	[[object.function]]
	name = "new_from_stringn"
	rename = "from_string"
	[[object.function]]
	name = "new_wrap_stringn"
	rename = "wrap_string"
	unsafe = true
	[[object.function]]
	name = "to_string"
	ignore = true
	[[object.function]]
	name = "ensure_unique_owner"
		[[object.function.return]]
		nullable = false

[[object]]
name = "Wp.SpaJsonParser"
status = "generate"
	[[object.function]]
	pattern = "(get|get_valist)"
	ignore = true
	[[object.function]]
	pattern = "(get_json)"
	manual = true
	[[object.function]]
	name = "get_null"
	rename = "null"
	[[object.function]]
	name = "new_array"
	rename = "new_array_unchecked"
	unsafe = true
	[[object.function]]
	name = "new_object"
	rename = "new_object_unchecked"
	unsafe = true
	[[object.function]]
	name = "new_undefined"
	rename = "new_undefined_unchecked"
	unsafe = true

[[object]]
name = "Wp.SpaJsonBuilder"
status = "generate"
trust_return_value_nullability = true
	[[object.function]]
	pattern = "(add|add_valist|add_from_string)"
	ignore = true
	[[object.function]]
	name = "add_from_stringn"
	rename = "add_from_string"
	[[object.function]]
	name = "add_json"
	rename = "add_spa_json"
	doc_hidden = true

[[object]]
name = "Wp.SpaPod"
status = "generate"
	[[object.function]]
	pattern = "(.*valist|new_choice|new_object|new_sequence|get_object|get_struct)"
	ignore = true
	[[object.function]]
	pattern = "(new_bytes|new_pointer|new_wrap|new_wrap_const|get_bytes|get_choice_type|get_pointer|get_spa_type|get_spa_pod|set_pointer)"
	manual = true
	[[object.function]]
	name = "new_iterator"
	visibility = "crate"

[[object]]
name = "Wp.SpaPodParser"
status = "generate"
	[[object.function]]
	pattern = "(get|get_bytes|get_pointer|get_valist)"
	ignore = true
	[[object.function]]
	pattern = "(new_object)"
	manual = true

[[object]]
name = "Wp.SpaPodBuilder"
status = "generate"
	[[object.function]]
	pattern = "(add|add_bytes|add_pointer|add_valist)"
	ignore = true
