[options]
library = "Wp"
version = "0.4"
target_path = "."
min_cfg_version = "0.4"
work_mode = "normal"
split_build_rs = true
generate_display_trait = false
trust_return_value_nullability = true
single_version_file = "sys/generate/src/Gir.version"
girs_directories = ["sys/generate/src", "gir-files"]

external_libraries = ["GLib", "GObject", "Gio"]
generate = [
	"Wp.Proxy",
	"Wp.GlobalProxy",
	"Wp.Plugin", "Wp.ComponentLoader",
	"Wp.SessionItem", "Wp.SessionItemFeatures",
	"Wp.SiLink", "Wp.SiLinkable", "Wp.SiFactory",
	"Wp.SpaDeviceFeatures",
	"Wp.State",
	"Wp.Dbus", "Wp.DbusFeatures",
	"Wp.ProxyFeatures",
	"Wp.PluginFeatures",
	"Wp.NodeFeatures",
	"Wp.Object",
	"Wp.Device", "Wp.Endpoint", "Wp.Factory", "Wp.Port",
	"Wp.ImplEndpoint",
	"Wp.FeatureActivationTransition",
	"Wp.SiEndpoint", "Wp.ImplMetadata",
	"Wp.ImplModule", "Wp.ImplNode",
	"Wp.InitFlags", "Wp.InterestMatch", "Wp.InterestMatchFlags",
	"Wp.LookupDirs",
	"Wp.MetadataFeatures", "Wp.Metadata",
]

manual = [
	"Wp.SpaIdTable", "Wp.SpaIdValue",
	"Wp.IteratorMethods",
	"GLib.Error", "GLib.Variant", "GLib.MainContext", "GLib.Source", "GLib.SourceFunc", "GLib.DestroyNotify", "GLib.Quark", "GLib.LogLevelFlags", "GLib.LogField", "GLib.LogWriterOutput",
	"GObject.Closure", "GObject.Value", "GObject.Object",
	"Gio.Cancellable", "Gio.AsyncReadyCallback", "Gio.AsyncResult",
	"Gio.DBusConnection", "Gio.BusType",
]

[[object]]
name = "Wp.SpaType"
status = "manual"
conversion_type = "scalar"

[[object]]
name = "Wp.Core"
status = "generate"
	[[object.function]]
	pattern = "(clone|get_pw_context|get_pw_core)"
	manual = true

[[object]]
name = "Wp.SiAcquisition"
status = "generate"
	[[object.function]]
	name = "acquire"
	manual = true

[[object]]
name = "Wp.SiAdapter"
status = "generate"
	[[object.function]]
	name = "set_ports_format"
	manual = true

[[object]]
name = "Wp.Transition"
status = "generate"
	[[object.function]]
	pattern = "(new|return_error)"
	manual = true

[[object]]
name = "Wp.SpaDevice"
status = "generate"
	[[object.function]]
	pattern = "(new_wrap|spa_device_handle)"
	manual = true

[[object]]
name = "Wp.SpaPodParser"
status = "generate"
	[[object.function]]
	name = "new_object"
	ignore = true

[[object]]
name = "Wp.Properties"
status = "generate"
	[[object.derive]]
	name = "PartialEq, Eq, PartialOrd, Ord, Hash" # defaults excluding Debug
	[[object.function]]
	pattern = "(.*valist|new|add_keys|add_keys_from_dict|setf|update_keys|update_keys_from_dict)"
	ignore = true
	[[object.function]]
	pattern = "(new_copy|new_copy_dict|new_take|new_wrap|new_wrap_dict|add_from_dict|peek_dict|to_pw_properties|unref_and_take_pw_properties|update_from_dict)"
	manual = true

[[object]]
name = "Wp.PropertiesItem"
status = "generate"
# TODO: work around gir bug, 0.14 omitted the entire struct properly
cfg_condition = 'feature = "v0_4_2"'

[[object]]
name = "Wp.Iterator"
status = "generate"
	[[object.function]]
	pattern = "(new|new_ptr_array|fold|foreach|get_user_data)"
	manual = true

[[object]]
name = "Wp.ObjectManager"
status = "generate"
	[[object.function]]
	pattern = "(add_interest|lookup|new_filtered_iterator)"
	ignore = true

[[object]]
name = "Wp.ObjectInterest"
status = "generate"
	[[object.function]]
	pattern = "(new|matches)"
	manual = true
	[[object.function]]
	name = "new_valist"
	ignore = true

[[object]]
name = "Wp.ObjectFeatures"
status = "manual"
conversion_type = "scalar"

[[object]]
name = "Wp.PipewireObject"
status = "generate"
	[[object.function]]
	name = "get_property"
	manual = true

[[object]]
name = "Wp.Client"
status = "generate"
	[[object.function]]
	name = "update_permissions"
	ignore = true

[[object]]
name = "Wp.Node"
status = "generate"
	[[object.function]]
	name = "get_state"
	manual = true
	[[object.function]]
	pattern = "(lookup_port|new_ports_filtered_iterator)"
	ignore = true

[[object]]
name = "Wp.Link"
status = "generate"
	[[object.function]]
	name = "get_state"
	manual = true

# enums

[[object]]
name = "Wp.ConstraintVerb"
status = "generate"
generate_display_trait = true

[[object]]
name = "Wp.ConstraintType"
status = "generate"
generate_display_trait = true

[[object]]
name = "Wp.Direction"
status = "generate"
generate_display_trait = true

[[object]]
name = "Wp.LibraryErrorEnum"
status = "generate"
generate_display_trait = true

[[object]]
name = "Wp.NodeState"
status = "generate"
generate_display_trait = true

[[object]]
name = "Wp.DBusState"
status = "generate"
generate_display_trait = true

[[object]]
name = "Wp.LinkState"
status = "generate"
generate_display_trait = true

[[object]]
name = "Wp.SiAdapterPortsState"
status = "generate"
generate_display_trait = true

[[object]]
name = "Wp.TransitionStep"
status = "generate"
generate_display_trait = true

# flags

[[object]]
name = "Wp.LinkFeatures"
status = "generate"
version = "" # fails to parse, so removes cfg
	[[object.member]]
	# instead, apply the version cfg to all defined bits instead
	pattern = ".*"
	version = "0.4.11"

# unsupported methods (mostly varargs fns)

[[object]]
name = "Wp.SpaJson"
status = "generate"
	[[object.function]]
	pattern = "(.*valist|new_array|new_object|object_get|parse_array|parse_object)"
	ignore = true
	[[object.function]]
	pattern = "(new_wrap|spa_json)"
	manual = true

[[object]]
name = "Wp.SpaJsonParser"
status = "generate"
	[[object.function]]
	pattern = "(get|get_valist)"
	ignore = true

[[object]]
name = "Wp.SpaJsonBuilder"
status = "generate"
	[[object.function]]
	pattern = "(add|add_valist)"
	ignore = true

[[object]]
name = "Wp.SpaPod"
status = "generate"
	[[object.function]]
	pattern = "(.*valist|new_choice|new_object|new_sequence|get_object|get_struct)"
	ignore = true
	[[object.function]]
	pattern = "(new_bytes|new_pointer|new_wrap|new_wrap_const|get_bytes|get_choice_type|get_pointer|get_spa_type|get_spa_pod|set_pointer)"
	manual = true

[[object]]
name = "Wp.SpaPodParser"
status = "generate"
	[[object.function]]
	pattern = "(get|get_bytes|get_pointer|get_valist)"
	ignore = true
	[[object.function]]
	pattern = "(new_object)"
	manual = true

[[object]]
name = "Wp.SpaPodBuilder"
status = "generate"
	[[object.function]]
	pattern = "(add|add_bytes|add_pointer|add_valist)"
	ignore = true
