= WirePlumber Rust Bindings
:source-highlighter: highlight.js
:crate: wireplumber
:release: main
:relative-tree:
:relative-blob:
:url-pw: https://pipewire.org/
:url-pw-api: https://docs.pipewire.org/page_api.html
:url-wp: https://pipewire.pages.freedesktop.org/wireplumber/index.html
:url-docs: https://arcnmx.github.io/wireplumber.rs/{release}/{crate}/
:url-docs-modules: {url-docs}#modules
:url-crates: https://crates.io/crates/{crate}
:badge-crates: https://img.shields.io/crates/v/{crate}.svg?style=flat-square
:badge-docs: https://img.shields.io/badge/API-docs-blue.svg?style=flat-square
:badge-license: https://img.shields.io/badge/license-MIT-ff69b4.svg?style=flat-square

link:{url-crates}[image:{badge-crates}["latest release",title="crates.io"]]
link:{url-docs}[image:{badge-docs}["docs",title="API documentation"]]
link:{relative-blob}COPYING[image:{badge-license}["MIT",title="License"]]

This crate provides a high-level interface to {url-pw}[PipeWire]'s {url-pw-api}[API] via {url-wp}[libwireplumber].
Explore the {url-docs}[crate documentation] and the various {url-docs-modules}[modules] for information on how to start using WirePlumber with Rust.

== Examples

Some link:{relative-tree}examples/[examples] are provided that can be built and run via Cargo:

[source,bash]
----
$ cargo run -p wp-examples --bin wpexec -- --help
... snip ...

# try out the default lua example:
$ cargo run -p wp-examples --bin wpexec

# or load the example plugin module:
$ cargo build --workspace --examples &&
  cargo run -p wp-examples --bin wpexec -- --type wireplumber
----

=== External

Projects using wireplumber.rs:

* https://github.com/arcnmx/wireplumber-scripts[WirePlumber Scripts] is a personal collection of plugins, some previously written as Lua scripts.

== Use Cases

This project aims to facilitate the following applications:

* Enabling Rust to be a viable language for writing session management logic as an alternative to the officially supported Lua scripting engine or GObject C APIs
* WirePlumber plugins that can augment or expose APIs for Lua configuration scripts to use
* Stand-alone pipewire clients as an alternative to https://gitlab.freedesktop.org/pipewire/pipewire-rs[pipewire-rs]
