// Generated by gir (https://github.com/gtk-rs/gir @ unstable-2021-11-21)
// from /nix/store/5njndanmnlsxkgl5yyrmkfs8a4909cxa-gobject-introspection-1.70.0-dev/share/gir-1.0 (@ ???)
// from /nix/store/h9500ckrbcbv20q4qsj87q3rnp01fmxx-wireplumber.gir/share/gir-1.0 (@ ???)
// DO NOT EDIT

pub fn version() -> &'static str {
if cfg!(feature = "v0_4_3") {
        "0.4.3"
    } else if cfg!(feature = "v0_4_2") {
        "0.4.2"
    } else {
        "0.4"
    }
}
