// Generated by gir (https://github.com/gtk-rs/gir @ c148542)
// from /nix/store/5njndanmnlsxkgl5yyrmkfs8a4909cxa-gobject-introspection-1.70.0-dev/share/gir-1.0 (@ ???)
// from /nix/store/h9500ckrbcbv20q4qsj87q3rnp01fmxx-wireplumber.gir/share/gir-1.0 (@ ???)
// DO NOT EDIT

use crate::Object;
use crate::Plugin;
use std::fmt;

glib::wrapper! {
    pub struct ComponentLoader(Object<ffi::WpComponentLoader, ffi::WpComponentLoaderClass>) @extends Plugin, Object;

    match fn {
        type_ => || ffi::wp_component_loader_get_type(),
    }
}

impl ComponentLoader {}

pub const NONE_COMPONENT_LOADER: Option<&ComponentLoader> = None;

impl fmt::Display for ComponentLoader {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("ComponentLoader")
    }
}
