// Generated by gir (https://github.com/gtk-rs/gir @ 0.14-2021-10-08)
// from /nix/store/ckm3aff1aarriil9qs3hi72sl7qq45jy-gobject-introspection-1.70.0-dev/share/gir-1.0 (@ ???)
// from /nix/store/z1ikgbblvkdm762c9kpayxdyw93036xz-wireplumber.gir/share/gir-1.0 (@ ???)
// DO NOT EDIT

use crate::GlobalProxy;
use crate::Object;
use crate::PipewireObject;
use crate::Proxy;

glib::wrapper! {
    #[doc(alias = "WpFactory")]
    pub struct Factory(Object<ffi::WpFactory, ffi::WpFactoryClass>) @extends GlobalProxy, Proxy, Object, @implements PipewireObject;

    match fn {
        type_ => || ffi::wp_factory_get_type(),
    }
}

impl Factory {}
