// Generated by gir (https://github.com/gtk-rs/gir @ unstable-2021-11-21)
// from /nix/store/1gli05cgwhqdc8papdgi4y98l2xzssmq-wireplumber.gir/share/gir-1.0 (@ ???)
// from /nix/store/5njndanmnlsxkgl5yyrmkfs8a4909cxa-gobject-introspection-1.70.0-dev/share/gir-1.0 (@ ???)
// DO NOT EDIT

use crate::ObjectFeatures;
use crate::Transition;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
    #[doc(alias = "WpFeatureActivationTransition")]
    pub struct FeatureActivationTransition(Object<ffi::WpFeatureActivationTransition, ffi::WpFeatureActivationTransitionClass>) @extends Transition;

    match fn {
        type_ => || ffi::wp_feature_activation_transition_get_type(),
    }
}

impl FeatureActivationTransition {
    #[doc(alias = "wp_feature_activation_transition_get_requested_features")]
    #[doc(alias = "get_requested_features")]
    pub fn requested_features(&self) -> ObjectFeatures {
        unsafe {
            ffi::wp_feature_activation_transition_get_requested_features(self.to_glib_none().0)
        }
    }
}

impl fmt::Display for FeatureActivationTransition {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("FeatureActivationTransition")
    }
}
