// Generated by gir (https://github.com/gtk-rs/gir @ 0.14-2021-10-08)
// from /nix/store/7i7hi0ivv21w1n2n5b9gy7lfrhnkis9p-wireplumber.gir/share/gir-1.0 (@ ???)
// from /nix/store/l8nlsw7p6xi30lna4gq3mvd574njnmly-gobject-introspection-1.70.0-dev/share/gir-1.0 (@ ???)
// DO NOT EDIT

use crate::ObjectFeatures;
use crate::Transition;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
    #[doc(alias = "WpFeatureActivationTransition")]
    pub struct FeatureActivationTransition(Object<ffi::WpFeatureActivationTransition, ffi::WpFeatureActivationTransitionClass>) @extends Transition, @implements gio::AsyncResult;

    match fn {
        type_ => || ffi::wp_feature_activation_transition_get_type(),
    }
}

impl FeatureActivationTransition {
    #[doc(alias = "wp_feature_activation_transition_get_requested_features")]
    #[doc(alias = "get_requested_features")]
    pub fn requested_features(&self) -> ObjectFeatures {
        unsafe {
            ffi::wp_feature_activation_transition_get_requested_features(self.to_glib_none().0)
        }
    }
}

impl fmt::Display for FeatureActivationTransition {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("FeatureActivationTransition")
    }
}
