// This file was generated by gir (https://github.com/gtk-rs/gir)
// DO NOT EDIT

use crate::ObjectFeatures;
use crate::Transition;
use glib::translate::*;

glib::wrapper! {
    #[doc(alias = "WpFeatureActivationTransition")]
    pub struct FeatureActivationTransition(Object<ffi::WpFeatureActivationTransition, ffi::WpFeatureActivationTransitionClass>) @extends Transition, @implements gio::AsyncResult;

    match fn {
        type_ => || ffi::wp_feature_activation_transition_get_type(),
    }
}

impl FeatureActivationTransition {
    #[doc(alias = "wp_feature_activation_transition_get_requested_features")]
    #[doc(alias = "get_requested_features")]
    pub fn requested_features(&self) -> ObjectFeatures {
        unsafe {
            from_glib(ffi::wp_feature_activation_transition_get_requested_features(self.to_glib_none().0))
        }
    }
}
