// This file was generated by gir (https://github.com/gtk-rs/gir)
// DO NOT EDIT

use crate::Core;
use crate::GlobalProxy;
use crate::Metadata;
use crate::Object;
use crate::Properties;
use crate::Proxy;
use glib::object::ObjectType as ObjectType_;
use glib::translate::*;
use glib::StaticType;

glib::wrapper! {
    #[doc(alias = "WpImplMetadata")]
    pub struct ImplMetadata(Object<ffi::WpImplMetadata, ffi::WpImplMetadataClass>) @extends Metadata, GlobalProxy, Proxy, Object;

    match fn {
        type_ => || ffi::wp_impl_metadata_get_type(),
    }
}

impl ImplMetadata {
    #[doc(alias = "wp_impl_metadata_new")]
    pub fn new(core: &Core) -> ImplMetadata {
        unsafe {
            from_glib_full(ffi::wp_impl_metadata_new(core.to_glib_none().0))
        }
    }

    #[cfg(any(feature = "v0_4_3", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "v0_4_3")))]
    #[doc(alias = "wp_impl_metadata_new_full")]
    pub fn new_full(core: &Core, name: Option<&str>, properties: Option<&Properties>) -> ImplMetadata {
        unsafe {
            from_glib_full(ffi::wp_impl_metadata_new_full(core.to_glib_none().0, name.to_glib_none().0, properties.to_glib_full()))
        }
    }

    pub fn name(&self) -> Option<glib::GString> {
        unsafe {
            let mut value = glib::Value::from_type(<glib::GString as StaticType>::static_type());
            glib::gobject_ffi::g_object_get_property(self.as_ptr() as *mut glib::gobject_ffi::GObject, b"name\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().expect("Return Value for property `name` getter")
        }
    }

    pub fn properties(&self) -> Option<Properties> {
        unsafe {
            let mut value = glib::Value::from_type(<Properties as StaticType>::static_type());
            glib::gobject_ffi::g_object_get_property(self.as_ptr() as *mut glib::gobject_ffi::GObject, b"properties\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().expect("Return Value for property `properties` getter")
        }
    }
}
