// Generated by gir (https://github.com/gtk-rs/gir @ unstable-2021-11-21)
// from /nix/store/1gli05cgwhqdc8papdgi4y98l2xzssmq-wireplumber.gir/share/gir-1.0 (@ ???)
// from /nix/store/5njndanmnlsxkgl5yyrmkfs8a4909cxa-gobject-introspection-1.70.0-dev/share/gir-1.0 (@ ???)
// DO NOT EDIT

use crate::Core;
use crate::Endpoint;
use crate::GlobalProxy;
use crate::Object;
use crate::PipewireObject;
use crate::Proxy;
use crate::SiEndpoint;
use glib::object::IsA;
use glib::object::ObjectType as ObjectType_;
use glib::translate::*;
use glib::StaticType;
use std::fmt;

glib::wrapper! {
    #[doc(alias = "WpImplEndpoint")]
    pub struct ImplEndpoint(Object<ffi::WpImplEndpoint, ffi::WpImplEndpointClass>) @extends Endpoint, GlobalProxy, Proxy, Object, @implements PipewireObject;

    match fn {
        type_ => || ffi::wp_impl_endpoint_get_type(),
    }
}

impl ImplEndpoint {
    #[doc(alias = "wp_impl_endpoint_new")]
    pub fn new(core: &Core, item: &impl IsA<SiEndpoint>) -> ImplEndpoint {
        unsafe {
            from_glib_full(ffi::wp_impl_endpoint_new(core.to_glib_none().0, item.as_ref().to_glib_none().0))
        }
    }

    pub fn item(&self) -> Option<SiEndpoint> {
        glib::ObjectExt::property(self, "item").unwrap().get().unwrap()
    }
}

impl fmt::Display for ImplEndpoint {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("ImplEndpoint")
    }
}
