// Generated by gir (https://github.com/gtk-rs/gir @ 0.14-2021-10-08)
// from /nix/store/7i7hi0ivv21w1n2n5b9gy7lfrhnkis9p-wireplumber.gir/share/gir-1.0 (@ ???)
// from /nix/store/l8nlsw7p6xi30lna4gq3mvd574njnmly-gobject-introspection-1.70.0-dev/share/gir-1.0 (@ ???)
// DO NOT EDIT


glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct IteratorMethods(Boxed<ffi::WpIteratorMethods>);

    match fn {
        copy => |ptr| glib::gobject_ffi::g_boxed_copy(ffi::wp_iterator_methods_get_type(), ptr as *mut _) as *mut ffi::WpIteratorMethods,
        free => |ptr| glib::gobject_ffi::g_boxed_free(ffi::wp_iterator_methods_get_type(), ptr as *mut _),
        type_ => || ffi::wp_iterator_methods_get_type(),
    }
}
