// This file was generated by gir (https://github.com/gtk-rs/gir)
// DO NOT EDIT

mod client;
pub use self::client::Client;

mod component_loader;
pub use self::component_loader::ComponentLoader;

mod core;
pub use self::core::Core;

#[cfg(feature = "v0_4_11")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_4_11")))]
mod dbus;
#[cfg(feature = "v0_4_11")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_4_11")))]
pub use self::dbus::Dbus;

mod device;
pub use self::device::Device;

mod endpoint;
pub use self::endpoint::Endpoint;

#[cfg(feature = "v0_4_5")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_4_5")))]
mod factory;
#[cfg(feature = "v0_4_5")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_4_5")))]
pub use self::factory::Factory;

mod feature_activation_transition;
pub use self::feature_activation_transition::FeatureActivationTransition;

mod global_proxy;
pub use self::global_proxy::GlobalProxy;

mod impl_endpoint;
pub use self::impl_endpoint::ImplEndpoint;

mod impl_metadata;
pub use self::impl_metadata::ImplMetadata;

#[cfg(feature = "v0_4_2")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_4_2")))]
mod impl_module;
#[cfg(feature = "v0_4_2")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_4_2")))]
pub use self::impl_module::ImplModule;

mod impl_node;
pub use self::impl_node::ImplNode;

mod link;
pub use self::link::Link;

mod metadata;
pub use self::metadata::Metadata;

mod node;
pub use self::node::Node;

mod object;
pub use self::object::Object;

mod object_manager;
pub use self::object_manager::ObjectManager;

mod pipewire_object;
pub use self::pipewire_object::PipewireObject;

mod plugin;
pub use self::plugin::Plugin;

mod port;
pub use self::port::Port;

mod proxy;
pub use self::proxy::Proxy;

mod session_item;
pub use self::session_item::SessionItem;

mod si_acquisition;
pub use self::si_acquisition::SiAcquisition;

mod si_adapter;
pub use self::si_adapter::SiAdapter;

mod si_endpoint;
pub use self::si_endpoint::SiEndpoint;

mod si_factory;
pub use self::si_factory::SiFactory;

mod si_link;
pub use self::si_link::SiLink;

mod si_linkable;
pub use self::si_linkable::SiLinkable;

mod spa_device;
pub use self::spa_device::SpaDevice;

mod state;
pub use self::state::State;

mod transition;
pub use self::transition::Transition;

mod iterator;
pub use self::iterator::Iterator;

mod object_interest;
pub use self::object_interest::ObjectInterest;

mod properties;
pub use self::properties::Properties;

#[cfg(feature = "v0_4_2")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_4_2")))]
mod properties_item;
#[cfg(feature = "v0_4_2")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_4_2")))]
pub use self::properties_item::PropertiesItem;

#[cfg(feature = "v0_4_8")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_4_8")))]
mod spa_json;
#[cfg(feature = "v0_4_8")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_4_8")))]
pub use self::spa_json::SpaJson;

#[cfg(feature = "v0_4_8")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_4_8")))]
mod spa_json_builder;
#[cfg(feature = "v0_4_8")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_4_8")))]
pub use self::spa_json_builder::SpaJsonBuilder;

#[cfg(feature = "v0_4_8")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_4_8")))]
mod spa_json_parser;
#[cfg(feature = "v0_4_8")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_4_8")))]
pub use self::spa_json_parser::SpaJsonParser;

mod spa_pod;
pub use self::spa_pod::SpaPod;

mod spa_pod_builder;
pub use self::spa_pod_builder::SpaPodBuilder;

mod spa_pod_parser;
pub use self::spa_pod_parser::SpaPodParser;

mod enums;
pub use self::enums::ConstraintType;
pub use self::enums::ConstraintVerb;
#[cfg(feature = "v0_4_11")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_4_11")))]
pub use self::enums::DBusState;
pub use self::enums::Direction;
pub use self::enums::LibraryErrorEnum;
#[cfg(feature = "v0_4_11")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_4_11")))]
pub use self::enums::LinkState;
pub use self::enums::NodeState;
#[cfg(feature = "v0_4_10")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_4_10")))]
pub use self::enums::SiAdapterPortsState;
pub use self::enums::TransitionStep;

mod flags;
#[cfg(feature = "v0_4_11")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_4_11")))]
pub use self::flags::DbusFeatures;
pub use self::flags::InitFlags;
pub use self::flags::InterestMatch;
pub use self::flags::InterestMatchFlags;
pub use self::flags::LinkFeatures;
pub use self::flags::LookupDirs;
pub use self::flags::MetadataFeatures;
pub use self::flags::NodeFeatures;
pub use self::flags::PluginFeatures;
pub use self::flags::ProxyFeatures;
pub use self::flags::SessionItemFeatures;
pub use self::flags::SpaDeviceFeatures;

#[doc(hidden)]
pub mod traits {
    pub use super::endpoint::EndpointExt;
    pub use super::global_proxy::GlobalProxyExt;
    pub use super::metadata::MetadataExt;
    pub use super::object::ObjectExt;
    pub use super::pipewire_object::PipewireObjectExt;
    pub use super::plugin::PluginExt;
    pub use super::proxy::ProxyExt;
    pub use super::session_item::SessionItemExt;
    pub use super::si_acquisition::SiAcquisitionExt;
    pub use super::si_adapter::SiAdapterExt;
    pub use super::si_endpoint::SiEndpointExt;
    pub use super::si_factory::SiFactoryExt;
    pub use super::si_link::SiLinkExt;
    pub use super::si_linkable::SiLinkableExt;
    pub use super::transition::TransitionExt;
}
