// Generated by gir (https://github.com/gtk-rs/gir @ unstable-2021-11-21)
// from /nix/store/1gli05cgwhqdc8papdgi4y98l2xzssmq-wireplumber.gir/share/gir-1.0 (@ ???)
// from /nix/store/5njndanmnlsxkgl5yyrmkfs8a4909cxa-gobject-introspection-1.70.0-dev/share/gir-1.0 (@ ???)
// DO NOT EDIT

use crate::Core;
use crate::Object;
use glib::object::IsA;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
    #[doc(alias = "WpPlugin")]
    pub struct Plugin(Object<ffi::WpPlugin, ffi::WpPluginClass>) @extends Object;

    match fn {
        type_ => || ffi::wp_plugin_get_type(),
    }
}

impl Plugin {
        pub const NONE: Option<&'static Plugin> = None;
    

    #[doc(alias = "wp_plugin_find")]
    pub fn find(core: &Core, plugin_name: &str) -> Option<Plugin> {
        unsafe {
            from_glib_full(ffi::wp_plugin_find(core.to_glib_none().0, plugin_name.to_glib_none().0))
        }
    }
}

pub trait PluginExt: 'static {
    #[doc(alias = "wp_plugin_get_name")]
    #[doc(alias = "get_name")]
    fn name(&self) -> Option<glib::GString>;

    #[doc(alias = "wp_plugin_register")]
    fn register(&self);
}

impl<O: IsA<Plugin>> PluginExt for O {
    fn name(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::wp_plugin_get_name(self.as_ref().to_glib_none().0))
        }
    }

    fn register(&self) {
        unsafe {
            ffi::wp_plugin_register(self.as_ref().to_glib_full());
        }
    }
}

impl fmt::Display for Plugin {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("Plugin")
    }
}
