// Generated by gir (https://github.com/gtk-rs/gir @ 0.14-2021-10-08)
// from /nix/store/7i7hi0ivv21w1n2n5b9gy7lfrhnkis9p-wireplumber.gir/share/gir-1.0 (@ ???)
// from /nix/store/l8nlsw7p6xi30lna4gq3mvd574njnmly-gobject-introspection-1.70.0-dev/share/gir-1.0 (@ ???)
// DO NOT EDIT

use crate::Direction;
use crate::GlobalProxy;
use crate::Object;
use crate::PipewireObject;
use crate::Proxy;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
    #[doc(alias = "WpPort")]
    pub struct Port(Object<ffi::WpPort, ffi::WpPortClass>) @extends GlobalProxy, Proxy, Object, @implements PipewireObject;

    match fn {
        type_ => || ffi::wp_port_get_type(),
    }
}

impl Port {
    #[doc(alias = "wp_port_get_direction")]
    #[doc(alias = "get_direction")]
    pub fn direction(&self) -> Direction {
        unsafe {
            from_glib(ffi::wp_port_get_direction(self.to_glib_none().0))
        }
    }
}

impl fmt::Display for Port {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("Port")
    }
}
