// Generated by gir (https://github.com/gtk-rs/gir @ c148542)
// from /nix/store/5njndanmnlsxkgl5yyrmkfs8a4909cxa-gobject-introspection-1.70.0-dev/share/gir-1.0 (@ ???)
// from /nix/store/h9500ckrbcbv20q4qsj87q3rnp01fmxx-wireplumber.gir/share/gir-1.0 (@ ???)
// DO NOT EDIT

use crate::Object;
use crate::SessionItem;
use glib::object::Cast;
use glib::object::IsA;
use glib::signal::connect_raw;
use glib::signal::SignalHandlerId;
use glib::translate::*;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;

glib::wrapper! {
    pub struct SiEndpoint(Interface<ffi::WpSiEndpoint, ffi::WpSiEndpointInterface>) @requires SessionItem, Object;

    match fn {
        type_ => || ffi::wp_si_endpoint_get_type(),
    }
}

pub const NONE_SI_ENDPOINT: Option<&SiEndpoint> = None;

pub trait SiEndpointExt: 'static {
    //#[doc(alias = "wp_si_endpoint_get_registration_info")]
    //#[doc(alias = "get_registration_info")]
    //fn registration_info(&self) -> /*Ignored*/Option<glib::Variant>;

    #[doc(alias = "endpoint-properties-changed")]
    fn connect_endpoint_properties_changed<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<SiEndpoint>> SiEndpointExt for O {
    //fn registration_info(&self) -> /*Ignored*/Option<glib::Variant> {
    //    unsafe { TODO: call ffi:wp_si_endpoint_get_registration_info() }
    //}

    #[doc(alias = "endpoint-properties-changed")]
    fn connect_endpoint_properties_changed<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn endpoint_properties_changed_trampoline<P, F: Fn(&P) + 'static>(this: *mut ffi::WpSiEndpoint, f: glib::ffi::gpointer)
            where P: IsA<SiEndpoint>
        {
            let f: &F = &*(f as *const F);
            f(&SiEndpoint::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"endpoint-properties-changed\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(endpoint_properties_changed_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }
}

impl fmt::Display for SiEndpoint {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("SiEndpoint")
    }
}
