// Generated by gir (https://github.com/gtk-rs/gir @ 0.14-2021-10-08)
// from /nix/store/7i7hi0ivv21w1n2n5b9gy7lfrhnkis9p-wireplumber.gir/share/gir-1.0 (@ ???)
// from /nix/store/l8nlsw7p6xi30lna4gq3mvd574njnmly-gobject-introspection-1.70.0-dev/share/gir-1.0 (@ ???)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "WpClientClass", sizeof(WpClientClass), alignof(WpClientClass));
    printf("%s;%zu;%zu\n", "WpComponentLoader", sizeof(WpComponentLoader), alignof(WpComponentLoader));
    printf("%s;%zu;%zu\n", "WpComponentLoaderClass", sizeof(WpComponentLoaderClass), alignof(WpComponentLoaderClass));
    printf("%s;%zu;%zu\n", "WpConstraintType", sizeof(WpConstraintType), alignof(WpConstraintType));
    printf("%s;%zu;%zu\n", "WpConstraintVerb", sizeof(WpConstraintVerb), alignof(WpConstraintVerb));
    printf("%s;%zu;%zu\n", "WpCoreClass", sizeof(WpCoreClass), alignof(WpCoreClass));
    printf("%s;%zu;%zu\n", "WpDeviceClass", sizeof(WpDeviceClass), alignof(WpDeviceClass));
    printf("%s;%zu;%zu\n", "WpDirection", sizeof(WpDirection), alignof(WpDirection));
    printf("%s;%zu;%zu\n", "WpEndpoint", sizeof(WpEndpoint), alignof(WpEndpoint));
    printf("%s;%zu;%zu\n", "WpEndpointClass", sizeof(WpEndpointClass), alignof(WpEndpointClass));
    printf("%s;%zu;%zu\n", "WpFactoryClass", sizeof(WpFactoryClass), alignof(WpFactoryClass));
    printf("%s;%zu;%zu\n", "WpFeatureActivationTransitionClass", sizeof(WpFeatureActivationTransitionClass), alignof(WpFeatureActivationTransitionClass));
    printf("%s;%zu;%zu\n", "WpGlobalProxy", sizeof(WpGlobalProxy), alignof(WpGlobalProxy));
    printf("%s;%zu;%zu\n", "WpGlobalProxyClass", sizeof(WpGlobalProxyClass), alignof(WpGlobalProxyClass));
    printf("%s;%zu;%zu\n", "WpImplEndpointClass", sizeof(WpImplEndpointClass), alignof(WpImplEndpointClass));
    printf("%s;%zu;%zu\n", "WpImplMetadataClass", sizeof(WpImplMetadataClass), alignof(WpImplMetadataClass));
    printf("%s;%zu;%zu\n", "WpImplModuleClass", sizeof(WpImplModuleClass), alignof(WpImplModuleClass));
    printf("%s;%zu;%zu\n", "WpImplNodeClass", sizeof(WpImplNodeClass), alignof(WpImplNodeClass));
    printf("%s;%zu;%zu\n", "WpInitFlags", sizeof(WpInitFlags), alignof(WpInitFlags));
    printf("%s;%zu;%zu\n", "WpInterestMatch", sizeof(WpInterestMatch), alignof(WpInterestMatch));
    printf("%s;%zu;%zu\n", "WpInterestMatchFlags", sizeof(WpInterestMatchFlags), alignof(WpInterestMatchFlags));
    printf("%s;%zu;%zu\n", "WpIteratorMethods", sizeof(WpIteratorMethods), alignof(WpIteratorMethods));
    printf("%s;%zu;%zu\n", "WpLibraryErrorEnum", sizeof(WpLibraryErrorEnum), alignof(WpLibraryErrorEnum));
    printf("%s;%zu;%zu\n", "WpLinkClass", sizeof(WpLinkClass), alignof(WpLinkClass));
    printf("%s;%zu;%zu\n", "WpLookupDirs", sizeof(WpLookupDirs), alignof(WpLookupDirs));
    printf("%s;%zu;%zu\n", "WpMetadata", sizeof(WpMetadata), alignof(WpMetadata));
    printf("%s;%zu;%zu\n", "WpMetadataClass", sizeof(WpMetadataClass), alignof(WpMetadataClass));
    printf("%s;%zu;%zu\n", "WpMetadataFeatures", sizeof(WpMetadataFeatures), alignof(WpMetadataFeatures));
    printf("%s;%zu;%zu\n", "WpNodeClass", sizeof(WpNodeClass), alignof(WpNodeClass));
    printf("%s;%zu;%zu\n", "WpNodeFeatures", sizeof(WpNodeFeatures), alignof(WpNodeFeatures));
    printf("%s;%zu;%zu\n", "WpNodeState", sizeof(WpNodeState), alignof(WpNodeState));
    printf("%s;%zu;%zu\n", "WpObject", sizeof(WpObject), alignof(WpObject));
    printf("%s;%zu;%zu\n", "WpObjectClass", sizeof(WpObjectClass), alignof(WpObjectClass));
    printf("%s;%zu;%zu\n", "WpObjectFeatures", sizeof(WpObjectFeatures), alignof(WpObjectFeatures));
    printf("%s;%zu;%zu\n", "WpObjectManagerClass", sizeof(WpObjectManagerClass), alignof(WpObjectManagerClass));
    printf("%s;%zu;%zu\n", "WpPipewireObjectInterface", sizeof(WpPipewireObjectInterface), alignof(WpPipewireObjectInterface));
    printf("%s;%zu;%zu\n", "WpPlugin", sizeof(WpPlugin), alignof(WpPlugin));
    printf("%s;%zu;%zu\n", "WpPluginClass", sizeof(WpPluginClass), alignof(WpPluginClass));
    printf("%s;%zu;%zu\n", "WpPluginFeatures", sizeof(WpPluginFeatures), alignof(WpPluginFeatures));
    printf("%s;%zu;%zu\n", "WpPortClass", sizeof(WpPortClass), alignof(WpPortClass));
    printf("%s;%zu;%zu\n", "WpProxy", sizeof(WpProxy), alignof(WpProxy));
    printf("%s;%zu;%zu\n", "WpProxyClass", sizeof(WpProxyClass), alignof(WpProxyClass));
    printf("%s;%zu;%zu\n", "WpProxyFeatures", sizeof(WpProxyFeatures), alignof(WpProxyFeatures));
    printf("%s;%zu;%zu\n", "WpSessionItem", sizeof(WpSessionItem), alignof(WpSessionItem));
    printf("%s;%zu;%zu\n", "WpSessionItemClass", sizeof(WpSessionItemClass), alignof(WpSessionItemClass));
    printf("%s;%zu;%zu\n", "WpSessionItemFeatures", sizeof(WpSessionItemFeatures), alignof(WpSessionItemFeatures));
    printf("%s;%zu;%zu\n", "WpSiAcquisitionInterface", sizeof(WpSiAcquisitionInterface), alignof(WpSiAcquisitionInterface));
    printf("%s;%zu;%zu\n", "WpSiAdapterInterface", sizeof(WpSiAdapterInterface), alignof(WpSiAdapterInterface));
    printf("%s;%zu;%zu\n", "WpSiEndpointInterface", sizeof(WpSiEndpointInterface), alignof(WpSiEndpointInterface));
    printf("%s;%zu;%zu\n", "WpSiFactory", sizeof(WpSiFactory), alignof(WpSiFactory));
    printf("%s;%zu;%zu\n", "WpSiFactoryClass", sizeof(WpSiFactoryClass), alignof(WpSiFactoryClass));
    printf("%s;%zu;%zu\n", "WpSiLinkInterface", sizeof(WpSiLinkInterface), alignof(WpSiLinkInterface));
    printf("%s;%zu;%zu\n", "WpSiLinkableInterface", sizeof(WpSiLinkableInterface), alignof(WpSiLinkableInterface));
    printf("%s;%zu;%zu\n", "WpSpaDeviceClass", sizeof(WpSpaDeviceClass), alignof(WpSpaDeviceClass));
    printf("%s;%zu;%zu\n", "WpSpaDeviceFeatures", sizeof(WpSpaDeviceFeatures), alignof(WpSpaDeviceFeatures));
    printf("%s;%zu;%zu\n", "WpSpaIdTable", sizeof(WpSpaIdTable), alignof(WpSpaIdTable));
    printf("%s;%zu;%zu\n", "WpSpaIdValue", sizeof(WpSpaIdValue), alignof(WpSpaIdValue));
    printf("%s;%zu;%zu\n", "WpStateClass", sizeof(WpStateClass), alignof(WpStateClass));
    printf("%s;%zu;%zu\n", "WpTransition", sizeof(WpTransition), alignof(WpTransition));
    printf("%s;%zu;%zu\n", "WpTransitionClass", sizeof(WpTransitionClass), alignof(WpTransitionClass));
    printf("%s;%zu;%zu\n", "WpTransitionStep", sizeof(WpTransitionStep), alignof(WpTransitionStep));
    return 0;
}
