// This file was generated by gir (https://github.com/gtk-rs/gir)
// DO NOT EDIT

pub fn version() -> &'static str {
if cfg!(feature = "v0_4_10") {
        "0.4.10"
    } else if cfg!(feature = "v0_4_8") {
        "0.4.8"
    } else if cfg!(feature = "v0_4_6") {
        "0.4.6"
    } else if cfg!(feature = "v0_4_5") {
        "0.4.5"
    } else if cfg!(feature = "v0_4_3") {
        "0.4.3"
    } else if cfg!(feature = "v0_4_2") {
        "0.4.2"
    } else {
        "0.4"
    }
}
