#!/usr/bin/env bash

# note: a pw_permission is actually 2x uint32
exec xmlstarlet ed \
	-i '///_:type[not(@name) and @c:type="pw_permission"]' -t attr -n name -v guint64 \
	-u '///_:constant[@c:type="WP_LOG_LEVEL_TRACE"]/@value' -v $((1<<8)) \
	-u '///_:constant[@c:type="WP_PIPEWIRE_OBJECT_FEATURES_ALL"]/@value' -v $((992|17)) \
	-i '///_:record[@c:type="WpIteratorMethods"]' -t attr -n glib:get-type -v wp_iterator_methods_get_type \
	-u '///_:record[@c:type="WpSpaPod"]/_:method[@c:identifier="wp_spa_pod_get_control"]//_:parameter[@name="ctl_type"]/@transfer-ownership' -v none \
	-u '///_:record[@c:type="WpSpaPod"]/_:method[@c:identifier="wp_spa_pod_get_property"]//_:parameter[@name="key"]/@transfer-ownership' -v none \
	-u '///_:record[@c:type="WpSpaPod"]/_:method[@c:identifier="wp_spa_pod_get_property"]//_:parameter[@name="value"]/@transfer-ownership' -v none \
	-u '///_:record[@c:type="WpSpaPod"]/_:method[@c:identifier="wp_spa_pod_get_string"]//_:parameter[@name="value"]/@transfer-ownership' -v none \
	-i '///_:class[@c:type="WpMetadata"]/_:method[@name="find"]/_:return-value' -t attr -n nullable -v 1 \
	-i '///_:class[@c:type="WpMetadata"]/_:method[@name="find"]//_:parameter[@name="type"]' -t attr -n nullable -v 1 \
	-i '///_:record[@c:type="WpSpaJsonParser"]/_:method[@name="get_json"]/_:return-value' -t attr -n nullable -v 1 \
	-i '///_:record[@c:type="WpSpaPodParser"]/_:method[@name="get_pod"]/_:return-value' -t attr -n nullable -v 1 \
	-i '///_:class[@name="SpaType"]/_:method[@name="get_values_table"]/_:return-value' -t attr -n nullable -v 1 \
	-i '///_:class[@name="SpaType"]/_:method[@name="name"]/_:return-value' -t attr -n nullable -v 1 \
	-i '///_:function[@name="find_file"]/_:return-value' -t attr -n nullable -v 1 \
	-i '///_:function[@name="spa_id_value_from_name"]/_:return-value' -t attr -n nullable -v 1 \
	-i '///_:function[@name="spa_id_value_from_number"]/_:return-value' -t attr -n nullable -v 1 \
	-i '///_:function[@name="spa_id_value_from_short_name"]/_:return-value' -t attr -n nullable -v 1 \
	-i '///_:class[@c:type="WpFactory"]' -t attr -n version -v 0.4.5 \
	-i '///_:record[@c:type="WpFactoryClass"]' -t attr -n version -v 0.4.5 \
	-i '///_:record[@c:type="WpSpaJson"]' -t attr -n version -v 0.4.8 \
	-i '///_:record[@c:type="WpSpaJsonParser"]' -t attr -n version -v 0.4.8 \
	-i '///_:record[@c:type="WpSpaJsonBuilder"]' -t attr -n version -v 0.4.8 \
	-i '///_:record[@c:type="WpSpaJson"]/_:constructor[@name="new_from_stringn"]' -t attr -n version -v 0.4.10 \
	-i '///_:enumeration[@c:type="WpSiAdapterPortsState"]' -t attr -n version -v 0.4.10 \
	-i '///_:interface[@c:type="WpSiAdapter"]/glib:signal[@name="adapter-ports-state-changed"]' -t attr -n version -v 0.4.10 \
	-i '///_:class[@c:type="WpDbus"]' -t attr -n version -v 0.4.11 \
	-i '///_:enumeration[@c:type="WpLinkState"]' -t attr -n version -v 0.4.11 \
	-i '///_:enumeration[@c:type="WpDBusState"]' -t attr -n version -v 0.4.11 \
	-i '///_:bitfield[@c:type="WpDbusFeatures"]' -t attr -n version -v 0.4.11 \
	-i '///_:bitfield[@c:type="WpLinkFeatures"]' -t attr -n version -v 0.4.11 \
	-i '///_:class[@c:type="WpCore"]/_:method[@name="get_vm_type"]' -t attr -n version -v 0.4.11 \
	-i '///_:class[@c:type="WpLink"]/_:property[@name="state"]' -t attr -n version -v 0.4.11 \
	-i '///_:class[@c:type="WpLink"]/glib:signal[@name="state-changed"]' -t attr -n version -v 0.4.11 \
	-i '///_:function[@name="get_library_version"]' -t attr -n version -v 0.4.12 \
	-i '///_:function[@name="get_library_api_version"]' -t attr -n version -v 0.4.12 \
	-u '//_:namespace[@name="Wp"]/@shared-library' -v wireplumber-0.4.so.0 \
	-i '/_:repository/_:package[not(@name)]' -t attr -n name -v wireplumber-0.4
